#Pruebas Proyecto 2
#exec -path=/home/samuel/Escritorio/Go/Proyecto2/entrada.script
rmdisk -path=/home/samuel/Escritorio/discoPrueba.dsk
mkdisk -size=3 -path=/home/samuel/Escritorio/discoPrueba.dsk -unit=m
fdisk -type=P -unit=m -size=1 -fit=BF -path="/home/samuel/Escritorio/discoPrueba.dsk" -name=ParticionX
mount -path=/home/samuel/Escritorio/discoPrueba.dsk -name=ParticionX
rep -id=08a1 -path="/home/samuel/Escritorio/Go/Proyecto2/Disk.pdf" -name=disk
mkfs -id=08a1 -type=full
rep -id=08a1 -path="/home/samuel/Escritorio/Go/Proyecto2/Tree.pdf" -name=tree